name: Build and Push Docker Image

on:
  push:
    branches: [ custom_auth ]

env:
  IMAGE_NAME: vat-labelstudio
  PYTHON_VERSION: '3.12'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Prepare Repository Names
      run: |
        echo "REPO_LOWER=${GITHUB_REPOSITORY_OWNER_PART,,}" >> $GITHUB_ENV
      env:
        GITHUB_REPOSITORY_OWNER_PART: ${{ github.repository_owner }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        push: true
        tags: ghcr.io/${{ env.REPO_LOWER }}/${{ env.IMAGE_NAME }}:custom-auth
        cache-from: type=gha
        cache-to: type=gha,mode=max
